### ISSUE TITLE
Need to update to moji 1.0.2

### ISSUE THREAD

**Issue by zhichaohu** [danainschool/moss-taps#9]
I was having the following error when running MossTaps. The error was gone after I replace moji-1.0.1.jar with version 1.0.2 (download here: https://zielke.it/moji/download.html).

--------------------------------------------------------------------------------------
The current essential settings for your Moss submissions are as follows:
Original directory (past projects/students/../files):
   data/Original
Current directory (current projects/students/../files):
   data/Current
Base directory (contains starter code to be ignored; may be empty:
   data/Base
Computer languages:
   Java
settings valid - ready to go!
Showing O_ projects
/……/data/Original/pa2
Showing C_ projects
/……/data/Current/pa2
starting SocketClient Java : data/Upload
uploading basefiles
uploading sourcefiles
sending query to moss.stanford.edu
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at it.zielke.moji.SocketClient.readFromServer(SocketClient.java:219)
	at it.zielke.moji.SocketClient.sendQuery(SocketClient.java:381)
	at edu.gatech.edtech.Submission.singleSubmit(Submission.java:100)
	at edu.gatech.edtech.Submission.submit(Submission.java:47)
	at edu.gatech.edtech.MossTaps.main(MossTaps.java:36)
Results created in MT_20170203_Java.csv

**Comment by AndreasArne** [comment]
Thank you, this solved a NullPointerException for me.
```
Exception in thread "main" java.lang.NullPointerException
        at it.zielke.moji.SocketClient.sendQuery(SocketClient.java:381)
        at edu.gatech.edtech.Submission.singleSubmit(Submission.java:100)
        at edu.gatech.edtech.Submission.submit(Submission.java:47)
        at edu.gatech.edtech.MossTaps.main(MossTaps.java:36)
```
